# Site settings
title: Lansing Tech Studio
email: contact@lansingtechstudio.org
description: >-
  Empowering youth through technology, robotics, and community service.
  Supporting FIRST LEGO League teams, hosting coding bootcamps, and making a difference.
baseurl: ""
url: "https://lansing-tech-studio.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - programs.md
  - outreach.md
  - resources.md
  - sponsors.md
  - contact.md

# Social media
github_username: Lansing-Tech-Studio
facebook_username: 61572896006614
youtube_username: "@LansingTechStudio"

# Custom variables
logo: /assets/images/logo.png
mission_statement: "The Lansing Tech Studio empowers the next generation by igniting their passion for technology, innovation, leadership, and service, cultivating tomorrowâ€™s leaders driven to shape a better future in their communities and the world."

# Collections
collections:
  team_bios:
    output: true
    permalink: /:collection/:name/
  blog_posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - SiteLayout.md
